title: yylhbb's blog
description: yylhbb's blog
author: yylhbb
logo: /yylhbb.github.io/static/img/avatar.png
github: https://github.com/yylhbb
about: 宅 

baseurl: "https://yylhbb.github.io/yylhbb.github.io"
url: "https://yylhbb.github.io/yylhbb.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]
